{
 "title": "Romax114 dashboard",
 "description": "Task-7",
 "time": { "from": "2025-07-27T13:14:59.017Z", "to": "2025-07-30T05:14:59.017Z" },
 "refresh": "auto",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node_info",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_info{node=\"minikube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Network_receive_bytes_total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{namespace=\"monitoring\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network_transmit_bytes_total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{instance=\"192.168.49.2:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Flowcontrol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Apiserver flowcontrol dispatch",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_dispatch_r{namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flowcontrol request execution seconds count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_execution_seconds_count{instance=\"192.168.49.2:8443\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "CPU usage (All cluster)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Disk usage (GB)",
   "type": "bargauge",
   "description": "Disk usage (GB)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) - sum(node_filesystem_avail_bytes{fstype=~\"ext4|xfs\"}))/1024/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Io Time",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 43 },
   "targets": [
    {
     "expr": "node_disk_io_time_seconds_total{namespace=\"monitoring\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(node_filesystem_avail_bytes{fstype=~\"ext4|xfs\"}) / sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "description": "Disk usage",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) - sum(node_filesystem_avail_bytes{fstype=~\"ext4|xfs\"}))/1024/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (GB)",
   "type": "bargauge",
   "description": "Memory usage (GB)",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}