apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort | default 30081 }}
    {{- end }}
  selector:
    app: {{ .Chart.Name }}