apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: '<your-email@example.com>'
      smtp_auth_username: '<username>'
      smtp_auth_password: '<password>'
      smtp_require_tls: false
    
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default-receiver'
      routes:
      - match:
          severity: critical
        receiver: 'critical-receiver'
      - match:
          severity: warning
        receiver: 'warning-receiver'
    
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: '<your-email@example.com>'
        subject: '[K8s Alert] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    
    - name: 'critical-receiver'
      email_configs:
      - to: '<your-email@example.com>'
        subject: '[CRITICAL] K8s Alert: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT!
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}
    
    - name: 'warning-receiver'
      email_configs:
      - to: '<your-email@example.com>'
        subject: '[WARNING] K8s Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}