apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  namespace: monitoring
  labels:
    app: stress-test
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu", "2", "--memory", "1G", "--timeout", "300s"]
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  restartPolicy: Never