# Base Jenkins configuration
controller:
  admin:
    existingSecret: "jenkins-admin-secret"
    userKey: "username"
    passwordKey: "password"

  # resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  serviceType: NodePort
  nodePort: 32000
  
  # Agent listener service (disabled - using custom service)
  agentListenerEnabled: false

  serviceAccount:
    create: true
    name: jenkins
    annotations: {}
  
  # RBAC configuration
  rbac:
    create: true
    readSecrets: false

  # Install Kubernetes plugin for agents
  installPlugins:
    - kubernetes:4358.vcfd9c5a_0a_f51
    - git:5.7.0
    - configuration-as-code:1971.vf9280461ea_89
    - credentials:1415.v831096eb_5534
    - job-dsl:1.93
    - structs:350.v3b_30f09f2363
    - script-security:1373.vb_b_4a_a_c26fa_00
    - eddsa-api:0.3.0.1-19.vc432d923e5ee
    - pipeline-groovy-lib:752.vdddedf804e72
    - pipeline-model-extensions:2.2255.v56a_15e805f12
    - pipeline-model-definition:2.2255.v56a_15e805f12
    - workflow-cps:4168.v7ea_f89c358b_d
    - pipeline-groovy-lib:752.vdddedf804e72
    - workflow-multibranch:806.vb_b_688f609ee9
    - workflow-aggregator:608.v67378e9d3db_1
    - credentials-binding:696.v256688029804
    - docker-workflow:621.va_73f881d9232
    - pipeline-stage-view:2.38
    - blueocean:1.27.21
    - sonar:2.18
    - email-ext:1916.vc954a_f86ff21
    - aws-credentials:248.v78a_dcfc9db_ff
    - amazon-ecr:1.151.vb_ca_71ddd0b_cf
    - kubernetes-cli:1.364.vadef8cb8b823
    - htmlpublisher:427

  numExecutors: 0
  executorMode: "NORMAL"
  
  # JCasC Configuration (based on working setup)
  JCasC:
    defaultConfig: true

persistence:
  enabled: true
  storageClass: jenkins-storage
  annotations: {}
  labels: {}
  accessMode: "ReadWriteOnce"
  size: "4Gi"
  dataSource: {}
  subPath:
  volumes: []
  mounts: []

# Enable agents for distributed builds
agent:
  enabled: true
  
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  
  # Agent pod settings
  containerCap: 10
  instanceCap: 2147483647
  podRetention: "Never"
  showRawYaml: true
  
  # Use existing service account created by controller
  # useDefaultServiceAccount: true
  
  # Agent connection settings
  kubernetesConnectTimeout: 5
  kubernetesReadTimeout: 15
  maxRequestsPerHostStr: "32"
  retentionTimeout: 5
  waitForPodSec: 600
  
  # Agent image
  image:
    registry: ""
    repository: "jenkins/inbound-agent"
    tag: "3309.v27b_9314fd1a_4-6"
  
  workingDir: "/home/jenkins/agent"
  nodeUsageMode: "NORMAL"
  componentName: "jenkins-agent"
  
  # Connection settings
  args: "${computer.jnlpmac} ${computer.name}"
  sideContainerName: "jnlp"
  connectTimeout: 100